import Head from 'next/head'
import Playlist from '../components/Playlist/Playlist'
import styles from '../styles/Home.module.css'

export default function Home({ playlist }) {
  console.log(playlist)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Watch {playlist.title}
        </h1>

        {playlist.description
          ? (<p className={styles.description}>{playlist.description}</p>)
          : ''}

        <div className={styles.grid}>
          <Playlist playlist={playlist} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.jwplayer.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Special thanks to JW Player
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  // Get video data from the given API.
  // Note that the data is fetched in getStaticProps, so if the API changes, the website needs to be rebuild.
  const playlist = await fetch('https://cdn.jwplayer.com/v2/playlists/iG6xB42W')
    .then(res => res.json())
  return {
    props: {
      playlist,
    },
  }
}
